{prog} installation on Ubuntu is farily straight forward. The OS being used for
this section is Ubuntu 14.04 ( +Trusty+ ) with the Unity desktop. Only an initial
update and upgrade was performed before starting the {prog} installatiion process.

==== ( [red]*Required* ) - Ubuntu Prerequisite Install
Before you can run {prog}, you will need a several packages in order to proceed.
There are two packages associated with {prog}:

[horizontal]
{flsdk-info}:: The main set of scripts
{flsdk-meta-info}:: Meta package to install dependencies

To install the dependencies and {prog}, open a terminal ( +Ctrl+Alt+T+ ) and
perform the following actions:

NOTE: The FLSDK-Meta package will install many packages. Some are specifically
for use with FLSDK, while the majority are required to compile all forms
of the FLDIGI application suite. Depending on your download speeds, this step
can take a few minutes to complete.

[source,bash]
-----
# In the terminal, type:
sudo add-apt-repository ppa:ki7mt/flsdk
sudo apt-get update

# Accept the PGP Key, then
sudo apt-get install flsdk-meta flsdk

# Finished

-----

==== Run After Installation
To run {prog} after installation, you can use the terminal, search Unity or
look through your menu system. For for the terminal:

[source,bash]
-----
# In the terminal, type:
flsdk

# Finished

-----

