{prog} is a set of command line scripts designed to ease the burden of compiling
{fldigi-info} and associated applications from source code. It also provides
a full set of tools for developers that want to enhance or further develop
{fldigi-info} applications.

This document _Is Not_ a replacement for the official {fldigi-wiki}, nor should 
it be considered official documentation. At best, it is a supplement too the
{fldigi-wiki}. In time, sections of this document, if deemed appropriate, may
be added to the {fldigi-wiki} provided the maintainers find it useful, in whole
or part.

=== Core Features
Beyond the standard tools each distribution provides, {prog} will add the 
following features:

* Menu driven build system for (11) primary applications
* Version check script ( Release, Alpha, Local Build )
* Unlimited options when manually building from the command line

=== Supported Builds
{prog} will build the following applications from the FLDIGI Suite:

NOTE: Click on the application name to view the _Official User Manual_ for
each application.

[horizontal]
{comptext-info}:: Used to compare two text streams
{comptty-info}:: Used to compare two RTTY streams
{flamp-info}:: Amateur Multi-cast Protocol
{fldigi-info}:: Digital modem program for Linux, Free-BSD, OS X, WinXP thru Win7
{flarq-info}:: Automatic Repeat request program
{fllog-info}:: Ham Radio logbook application for casual operating
{flmsg-info}:: Simple forms editor for the amateur radio supported standard message formats.
{flnet-info}:: Real time tool to assist Net Control Operators in managing net activities.
{flrig-info}:: Transceiver control program to be used stand alone or with FLDIGI
{flwkey-info}:: Simple interface to the {winkey} series of CW code generators
{flwrap-info}:: Application that encapsulates a text, image, or a binary files
{linsim-info}:: Tool for Amateur Radio Digital Mode evaluation under varying HF propogation conditions

=== Distributions
The following distributions are currently supported:

* Debian / Mint / UBuntu
* Raspbian (Debian Wheezy, Jessie)
* Others ( where dependencies can be met )

NOTE: As new package lists are made available, additional Linux distributions
will added to the supported distribution list. If you have a particular
distribution you would like added, send an email to the {linuxham-group},
detailing all the required dependencies and any special configuration
details.

